In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Requirement already up-to-date: sklearn in /Users/alicesartori/opt/anaconda3/lib/python3.8/site-packages (0.0)


In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import seed
seed(1)

In [4]:
import tensorflow as tf

# Read the CSV and Perform Basic Data Cleaning

What are exoplanets?
Exoplanets are planets beyond our own solar system. Thousands have been discovered in the past two decades, mostly with NASA’s Kepler Space Telescope.

These exoplanets come in a huge variety of sizes and orbits. Some are gigantic planets hugging close to their parent stars; others are icy, some rocky. NASA and other agencies are looking for a special kind of planet: one that’s the same size as Earth, orbiting a sun-like star in the habitable zone.

The habitable zone is the area around a star where it is not too hot and not too cold for liquid water to exist on the surface of surrounding planets. Imagine if Earth was where Pluto is. The Sun would be barely visible (about the size of a pea) and Earth’s ocean and much of its atmosphere would freeze.

In [5]:
data= pd.read_csv("exoplanet_data.csv")
data

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0          CONFIRMED              0              0              0   
1     FALSE POSITIVE              0              1              0   
2     FALSE POSITIVE              0              1              0   
3          CONFIRMED              0              0              0   
4          CONFIRMED              0              0              0   
...              ...            ...            ...            ...   
6986  FALSE POSITIVE              0              0              0   
6987  FALSE POSITIVE              0              1              1   
6988       CANDIDATE              0              0              0   
6989  FALSE POSITIVE              0              0              1   
6990  FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
0                 0   54.418383     2.479000e-04    -2.479000e-04   
1                 0   19.899140     1.490000e-05    -1.490000e-05   
2                 0    1.736952     2.630000e-07    -2.630000e-07   
3                 0    2.525592     3.760000e-06    -3.760000e-06   
4                 0    4.134435     1.050000e-05    -1.050000e-05   
...             ...         ...              ...              ...   
6986              1    8.589871     1.846000e-04    -1.846000e-04   
6987              0    0.527699     1.160000e-07    -1.160000e-07   
6988              0    1.739849     1.780000e-05    -1.780000e-05   
6989              0    0.681402     2.430000e-06    -2.430000e-06   
6990              1    4.856035     6.360000e-05    -6.360000e-05   

      koi_time0bk  koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  \
0      162.513840          0.003520  ...             -81      4.467   
1      175.850252          0.000581  ...            -176      4.544   
2      170.307565          0.000115  ...            -174      4.564   
3      171.595550          0.001130  ...            -211      4.438   
4      172.979370          0.001900  ...            -232      4.486   
...           ...               ...  ...             ...        ...   
6986   132.016100          0.015700  ...            -152      4.296   
6987   131.705093          0.000170  ...            -166      4.529   
6988   133.001270          0.007690  ...            -220      4.444   
6989   132.181750          0.002850  ...            -236      4.447   
6990   135.993300          0.010800  ...            -225      4.385   

      koi_slogg_err1  koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2  \
0              0.064          -0.096     0.927          0.105         -0.061   
1              0.044          -0.176     0.868          0.233         -0.078   
2              0.053          -0.168     0.791          0.201         -0.067   
3              0.070          -0.210     1.046          0.334         -0.133   
4              0.054          -0.229     0.972          0.315         -0.105   
...              ...             ...       ...            ...            ...   
6986           0.231          -0.189     1.088          0.313         -0.228   
6987           0.035          -0.196     0.903          0.237         -0.079   
6988           0.056          -0.224     1.031          0.341         -0.114   
6989           0.056          -0.224     1.041          0.341         -0.114   
6990           0.054          -0.216     1.193          0.410         -0.137   

             ra        dec  koi_kepmag  
0     291.93423  48.141651      15.347  
1     297.00482  48.134129      15.436  
2     285.53461  48.285210      15.597  
3     288.75488  48.226200      15.509  
4     296.28613  48.224670      15.714  
...         ...        ...         ...  
6986  298.74921  46.973351      14.478  
6987  297.18875  47.093819      14.082  
6988  286.50937  47.163219      14.757  
6989  294.16489  47.176281      15.385  
6990  297.00977  47.121021      14.826  

[6991 rows x 41 columns]

In [6]:
len(list(data.columns))

41

# Data Pre-Processing

In [7]:
#get the info on the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6991 entries, 0 to 6990
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   koi_disposition    6991 non-null   object 
 1   koi_fpflag_nt      6991 non-null   int64  
 2   koi_fpflag_ss      6991 non-null   int64  
 3   koi_fpflag_co      6991 non-null   int64  
 4   koi_fpflag_ec      6991 non-null   int64  
 5   koi_period         6991 non-null   float64
 6   koi_period_err1    6991 non-null   float64
 7   koi_period_err2    6991 non-null   float64
 8   koi_time0bk        6991 non-null   float64
 9   koi_time0bk_err1   6991 non-null   float64
 10  koi_time0bk_err2   6991 non-null   float64
 11  koi_impact         6991 non-null   float64
 12  koi_impact_err1    6991 non-null   float64
 13  koi_impact_err2    6991 non-null   float64
 14  koi_duration       6991 non-null   float64
 15  koi_duration_err1  6991 non-null   float64
 16  koi_duration_err2  6991 

In [8]:
data['koi_disposition'].unique()

array(['CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE'], dtype=object)

In [9]:
#Check for missing values, if there is any. Here there are not missing values
data.isnull().sum().sum()

0

# Select your features (columns)

In [10]:
# # #first thing that we do is to separate out the label and the dataframe and select the features.
# #This will also be used as your x values.

# NOTE: I tried selecting my columns using data[data.columns.drop(list(data.filter(regex ='err')))], but the informative content must
#have been less to build the model and I obtained a lower accurancy for both models

# 55/55 - 0s - loss: 0.3454 - accuracy: 0.8490
# Normal Neural Network - Loss: 0.3453817367553711, Accuracy: 0.8489702343940735
        
# 55/55 - 0s - loss: 0.3404 - accuracy: 0.8570
# Deep Neural Network - Loss: 0.3403897285461426, Accuracy: 0.8569794297218323

In [11]:
#first thing to do is to separate out the label from the numerical dataframe
X = data.drop("koi_disposition", axis=1)
y = data["koi_disposition"]
#Imput is the X dataset. 
print(X.shape, y.shape)

(6991, 40) (6991,)


In [12]:
#I take a look at my variables
X

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0                 0              0              0              0   54.418383   
1                 0              1              0              0   19.899140   
2                 0              1              0              0    1.736952   
3                 0              0              0              0    2.525592   
4                 0              0              0              0    4.134435   
...             ...            ...            ...            ...         ...   
6986              0              0              0              1    8.589871   
6987              0              1              1              0    0.527699   
6988              0              0              0              0    1.739849   
6989              0              0              1              0    0.681402   
6990              0              0              1              1    4.856035   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
0        2.479000e-04    -2.479000e-04   162.513840          0.003520   
1        1.490000e-05    -1.490000e-05   175.850252          0.000581   
2        2.630000e-07    -2.630000e-07   170.307565          0.000115   
3        3.760000e-06    -3.760000e-06   171.595550          0.001130   
4        1.050000e-05    -1.050000e-05   172.979370          0.001900   
...               ...              ...          ...               ...   
6986     1.846000e-04    -1.846000e-04   132.016100          0.015700   
6987     1.160000e-07    -1.160000e-07   131.705093          0.000170   
6988     1.780000e-05    -1.780000e-05   133.001270          0.007690   
6989     2.430000e-06    -2.430000e-06   132.181750          0.002850   
6990     6.360000e-05    -6.360000e-05   135.993300          0.010800   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0            -0.003520  ...             -81      4.467           0.064   
1            -0.000581  ...            -176      4.544           0.044   
2            -0.000115  ...            -174      4.564           0.053   
3            -0.001130  ...            -211      4.438           0.070   
4            -0.001900  ...            -232      4.486           0.054   
...                ...  ...             ...        ...             ...   
6986         -0.015700  ...            -152      4.296           0.231   
6987         -0.000170  ...            -166      4.529           0.035   
6988         -0.007690  ...            -220      4.444           0.056   
6989         -0.002850  ...            -236      4.447           0.056   
6990         -0.010800  ...            -225      4.385           0.054   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0             -0.096     0.927          0.105         -0.061  291.93423   
1             -0.176     0.868          0.233         -0.078  297.00482   
2             -0.168     0.791          0.201         -0.067  285.53461   
3             -0.210     1.046          0.334         -0.133  288.75488   
4             -0.229     0.972          0.315         -0.105  296.28613   
...              ...       ...            ...            ...        ...   
6986          -0.189     1.088          0.313         -0.228  298.74921   
6987          -0.196     0.903          0.237         -0.079  297.18875   
6988          -0.224     1.031          0.341         -0.114  286.50937   
6989          -0.224     1.041          0.341         -0.114  294.16489   
6990          -0.216     1.193          0.410         -0.137  297.00977   

            dec  koi_kepmag  
0     48.141651      15.347  
1     48.134129      15.436  
2     48.285210      15.597  
3     48.226200      15.509  
4     48.224670      15.714  
...         ...         ...  
6986  46.973351      14.478  
6987  47.093819      14.082  
6988  47.163219      14.757  
6989  47.176281      15.385  
6990  47.121021      14.826  

[6991 rows x 40 c

In [13]:
y.unique()

array(['CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE'], dtype=object)

# Pre-processing

In [14]:
# Import the necessaried dependecies 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [15]:
# Use train_test_split to create training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1)

In [16]:
#It is really important to scale our data before using multilayer perceptron models. Using MinMaxscaler (or StandardScaler)in this case
#Without scaling, it is often difficult for the training cycle to converge. 

X_scaler = MinMaxScaler().fit(X_train)

#Remember to scale both the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [17]:
# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [18]:
# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)


In [19]:
y_test_categorical

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [20]:
# Creating our Model
# We must first decide what kind of model to apply to our data.
# For categorical data, we use a classifier model.
# In this example, we will use a classifier to build the following network:

# Create a Normal Neural Network Model

In [21]:
# We first need to create a sequential model object
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [22]:
# Next, we add our first layer. This layer requires you to specify both the number of inputs 
#and the number of nodes that you want in the hidden layer.
model_nn = Sequential()
model_nn.add(Dense(units=100, activation='relu', input_dim=40))
model_nn.add(Dense(units=100, activation='relu'))
model_nn.add(Dense(units=3, activation='softmax'))

# Our final layer is the output layer. Here, we need to specify the activation function (typically softmax for classification) 
# and the number of classes (labels) that we are trying to predict (3) 

In [23]:
# Compile the model
model_nn.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [24]:
model_nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               4100      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 303       
Total params: 14,503
Trainable params: 14,503
Non-trainable params: 0
_________________________________________________________________


In [25]:
#Finally, we train our model using our training data. Training consists of updating our weights using our optimizer and loss function. 
#we choose 60 iterations (loops) of training that are called epochs.
#We also choose to shuffle our training data and increase the detail printed out during each training cycle.
model_nn.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=2
)

Epoch 1/60
164/164 - 1s - loss: 0.5912 - accuracy: 0.7118
Epoch 2/60
164/164 - 0s - loss: 0.3861 - accuracy: 0.7999
Epoch 3/60
164/164 - 0s - loss: 0.3699 - accuracy: 0.8056
Epoch 4/60
164/164 - 0s - loss: 0.3586 - accuracy: 0.8205
Epoch 5/60
164/164 - 0s - loss: 0.3510 - accuracy: 0.8259
Epoch 6/60
164/164 - 0s - loss: 0.3432 - accuracy: 0.8375
Epoch 7/60
164/164 - 0s - loss: 0.3412 - accuracy: 0.8344
Epoch 8/60
164/164 - 0s - loss: 0.3323 - accuracy: 0.8423
Epoch 9/60
164/164 - 0s - loss: 0.3293 - accuracy: 0.8453
Epoch 10/60
164/164 - 0s - loss: 0.3244 - accuracy: 0.8446
Epoch 11/60
164/164 - 0s - loss: 0.3221 - accuracy: 0.8528
Epoch 12/60
164/164 - 0s - loss: 0.3154 - accuracy: 0.8581
Epoch 13/60
164/164 - 0s - loss: 0.3114 - accuracy: 0.8594
Epoch 14/60
164/164 - 0s - loss: 0.3156 - accuracy: 0.8566
Epoch 15/60
164/164 - 0s - loss: 0.3073 - accuracy: 0.8606
Epoch 16/60
164/164 - 0s - loss: 0.3054 - accuracy: 0.8661
Epoch 17/60
164/164 - 0s - loss: 0.3075 - accuracy: 0.8602
Epoch 

# Deep Learning Model
For this network, we simply add an additional hidden layer of 40 nodes

In [26]:
deep_model = Sequential()
deep_model.add(Dense(units=100, activation='relu', input_dim=40))
deep_model.add(Dense(units=100, activation='relu'))
deep_model.add(Dense(units=60, activation='relu'))
deep_model.add(Dense(units=3, activation='softmax'))

In [27]:
deep_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 100)               4100      
_________________________________________________________________
dense_4 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_5 (Dense)              (None, 60)                6060      
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 183       
Total params: 20,443
Trainable params: 20,443
Non-trainable params: 0
_________________________________________________________________


In [28]:
# compile and train
deep_model.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=60,
    shuffle=True,
    verbose=2
)

Epoch 1/60
164/164 - 1s - loss: 0.5190 - accuracy: 0.7292
Epoch 2/60
164/164 - 0s - loss: 0.3740 - accuracy: 0.8114
Epoch 3/60
164/164 - 0s - loss: 0.3645 - accuracy: 0.8123
Epoch 4/60
164/164 - 0s - loss: 0.3520 - accuracy: 0.8278
Epoch 5/60
164/164 - 0s - loss: 0.3409 - accuracy: 0.8335
Epoch 6/60
164/164 - 0s - loss: 0.3429 - accuracy: 0.8343
Epoch 7/60
164/164 - 0s - loss: 0.3349 - accuracy: 0.8375
Epoch 8/60
164/164 - 0s - loss: 0.3312 - accuracy: 0.8419
Epoch 9/60
164/164 - 0s - loss: 0.3219 - accuracy: 0.8533
Epoch 10/60
164/164 - 0s - loss: 0.3141 - accuracy: 0.8554
Epoch 11/60
164/164 - 0s - loss: 0.3247 - accuracy: 0.8425
Epoch 12/60
164/164 - 0s - loss: 0.3139 - accuracy: 0.8556
Epoch 13/60
164/164 - 0s - loss: 0.3032 - accuracy: 0.8610
Epoch 14/60
164/164 - 0s - loss: 0.3014 - accuracy: 0.8611
Epoch 15/60
164/164 - 0s - loss: 0.3051 - accuracy: 0.8623
Epoch 16/60
164/164 - 0s - loss: 0.3004 - accuracy: 0.8650
Epoch 17/60
164/164 - 0s - loss: 0.2976 - accuracy: 0.8652
Epoch 

# Quantifying the accuracy for both Models
We use our testing data to validate our model. This is how we determine the validity of our model (i.e. the ability to predict new and previously unseen data points)

In [29]:
#first model 
model_loss, model_accuracy = model_nn.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

55/55 - 0s - loss: 0.2522 - accuracy: 0.8867
Normal Neural Network - Loss: 0.25215160846710205, Accuracy: 0.8867276906967163


In [30]:
#deep leanring model more precise, more accuracy
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

55/55 - 0s - loss: 0.2780 - accuracy: 0.8822
Deep Neural Network - Loss: 0.27796798944473267, Accuracy: 0.8821510076522827


# Make Predictions - Normal Neural Network 

In [31]:
encoded_predictions = model_nn.predict_classes(X_test_scaled)

/Users/alicesartori/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [32]:
encoded_predictions

array([1, 2, 2, ..., 2, 2, 0])

In [33]:
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [34]:
prediction_labels

array(['CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', ...,
       'FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE'], dtype=object)

In [35]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test)}")

Predicted classes: ['CONFIRMED' 'FALSE POSITIVE' 'FALSE POSITIVE' ... 'FALSE POSITIVE'
 'FALSE POSITIVE' 'CANDIDATE']
Actual Labels: ['CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE', 'CANDIDATE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'CANDIDATE', 'CONFIRMED', 'CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE', 'CONFIRMED', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED'

In [36]:
pd.DataFrame({"Prediction": prediction_labels, "Actual": y_test}).reset_index(drop=True)

Prediction          Actual
0          CONFIRMED       CONFIRMED
1     FALSE POSITIVE  FALSE POSITIVE
2     FALSE POSITIVE  FALSE POSITIVE
3          CONFIRMED       CONFIRMED
4     FALSE POSITIVE  FALSE POSITIVE
...              ...             ...
1743  FALSE POSITIVE  FALSE POSITIVE
1744       CONFIRMED       CONFIRMED
1745  FALSE POSITIVE  FALSE POSITIVE
1746  FALSE POSITIVE  FALSE POSITIVE
1747       CANDIDATE       CANDIDATE

[1748 rows x 2 columns]

#  I make a confusion matrix and then a classification report to describe the performance by comparing the predicted and actual values

In [37]:
target_names = ['CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE']

In [38]:
import numpy as np
rounded_labels=np.argmax(y_test_categorical, axis=1)
rounded_labels

array([1, 2, 2, ..., 2, 2, 0])

In [39]:
tf.math.confusion_matrix(rounded_labels,encoded_predictions)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[352,  49,   3],
       [138, 292,   5],
       [  1,   2, 906]], dtype=int32)>

In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(rounded_labels,encoded_predictions)
cm

array([[352,  49,   3],
       [138, 292,   5],
       [  1,   2, 906]])

In [41]:
from sklearn.metrics import classification_report
print(classification_report(rounded_labels,encoded_predictions, target_names=target_names))

                precision    recall  f1-score   support

     CONFIRMED       0.72      0.87      0.79       404
FALSE POSITIVE       0.85      0.67      0.75       435
     CANDIDATE       0.99      1.00      0.99       909

      accuracy                           0.89      1748
     macro avg       0.85      0.85      0.84      1748
  weighted avg       0.89      0.89      0.89      1748



# Deep Neural Network

In [42]:
encoded_predictions = deep_model.predict_classes(X_test_scaled)

/Users/alicesartori/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [43]:
encoded_predictions

array([1, 2, 2, ..., 2, 2, 0])

In [44]:
prediction_labels = label_encoder.inverse_transform(encoded_predictions)

In [45]:
prediction_labels

array(['CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', ...,
       'FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE'], dtype=object)

In [46]:
print(f"Predicted classes: {prediction_labels}")
print(f"Actual Labels: {list(y_test)}")

Predicted classes: ['CONFIRMED' 'FALSE POSITIVE' 'FALSE POSITIVE' ... 'FALSE POSITIVE'
 'FALSE POSITIVE' 'CANDIDATE']
Actual Labels: ['CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE', 'CANDIDATE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'CANDIDATE', 'CONFIRMED', 'CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE', 'CONFIRMED', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'CANDIDATE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CANDIDATE', 'FALSE POSITIVE', 'CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED'

In [47]:
pd.DataFrame({"Prediction": prediction_labels, "Actual": y_test}).reset_index(drop=True)

Prediction          Actual
0          CONFIRMED       CONFIRMED
1     FALSE POSITIVE  FALSE POSITIVE
2     FALSE POSITIVE  FALSE POSITIVE
3          CONFIRMED       CONFIRMED
4     FALSE POSITIVE  FALSE POSITIVE
...              ...             ...
1743  FALSE POSITIVE  FALSE POSITIVE
1744       CONFIRMED       CONFIRMED
1745  FALSE POSITIVE  FALSE POSITIVE
1746  FALSE POSITIVE  FALSE POSITIVE
1747       CANDIDATE       CANDIDATE

[1748 rows x 2 columns]

In [48]:
rounded_labels=np.argmax(y_test_categorical, axis=1)
rounded_labels

array([1, 2, 2, ..., 2, 2, 0])

In [49]:
tf.math.confusion_matrix(rounded_labels,encoded_predictions)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[360,  39,   5],
       [154, 276,   5],
       [  1,   2, 906]], dtype=int32)>

In [50]:
cm = confusion_matrix(rounded_labels,encoded_predictions)
cm

array([[360,  39,   5],
       [154, 276,   5],
       [  1,   2, 906]])

In [51]:
print(classification_report(rounded_labels,encoded_predictions, target_names=target_names))

                precision    recall  f1-score   support

     CONFIRMED       0.70      0.89      0.78       404
FALSE POSITIVE       0.87      0.63      0.73       435
     CANDIDATE       0.99      1.00      0.99       909

      accuracy                           0.88      1748
     macro avg       0.85      0.84      0.84      1748
  weighted avg       0.89      0.88      0.88      1748



In [52]:
# Compare metrics and determine best model
model_nn.save("Neural_Network.h5")

# See how another algorithm perform: I choose Random Forest

In [53]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8695652173913043

In [54]:
# Create a random forest classifier
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9124713958810069

In [55]:
# Get the features
feature_names = X.columns
feature_names

Index(['koi_fpflag_nt', 'koi_fpflag_ss', 'koi_fpflag_co', 'koi_fpflag_ec',
       'koi_period', 'koi_period_err1', 'koi_period_err2', 'koi_time0bk',
       'koi_time0bk_err1', 'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1',
       'koi_impact_err2', 'koi_duration', 'koi_duration_err1',
       'koi_duration_err2', 'koi_depth', 'koi_depth_err1', 'koi_depth_err2',
       'koi_prad', 'koi_prad_err1', 'koi_prad_err2', 'koi_teq', 'koi_insol',
       'koi_insol_err1', 'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_steff', 'koi_steff_err1', 'koi_steff_err2', 'koi_slogg',
       'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad', 'koi_srad_err1',
       'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='object')

In [56]:
# Random Forests in sklearn will automatically calculate feature importance
importances = rf.feature_importances_
importances

array([0.09934303, 0.06744889, 0.10443898, 0.03622968, 0.02027327,
       0.01578521, 0.01675502, 0.01386796, 0.02112372, 0.02243325,
       0.01919622, 0.01026138, 0.01119273, 0.02343446, 0.03495058,
       0.02965447, 0.02152413, 0.01370947, 0.01293314, 0.05121264,
       0.02830035, 0.04086544, 0.01501225, 0.01663247, 0.02224511,
       0.01449649, 0.05650953, 0.0030213 , 0.00987801, 0.03239132,
       0.02413784, 0.00891956, 0.00909118, 0.00938124, 0.00894179,
       0.01067557, 0.00881834, 0.01233262, 0.01196527, 0.0106161 ])

In [57]:
# We can sort the features by their importance
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.1044389801827151, 'koi_fpflag_co'),
 (0.09934302919316025, 'koi_fpflag_nt'),
 (0.06744889196220984, 'koi_fpflag_ss'),
 (0.05650953031171928, 'koi_model_snr'),
 (0.05121263933390322, 'koi_prad'),
 (0.04086544132793495, 'koi_prad_err2'),
 (0.036229684638157234, 'koi_fpflag_ec'),
 (0.03495058064337846, 'koi_duration_err1'),
 (0.03239131798289577, 'koi_steff_err1'),
 (0.029654471865608566, 'koi_duration_err2'),
 (0.028300351768308096, 'koi_prad_err1'),
 (0.024137837597400683, 'koi_steff_err2'),
 (0.023434460916419222, 'koi_duration'),
 (0.02243325220586789, 'koi_time0bk_err2'),
 (0.022245108979729408, 'koi_insol_err1'),
 (0.021524132960127187, 'koi_depth'),
 (0.02112371537264127, 'koi_time0bk_err1'),
 (0.020273271691137018, 'koi_period'),
 (0.019196223220638065, 'koi_impact'),
 (0.01675501954361788, 'koi_period_err2'),
 (0.016632471650482778, 'koi_insol'),
 (0.01578520919391726, 'koi_period_err1'),
 (0.01501224589914684, 'koi_teq'),
 (0.014496489154186538, 'koi_insol_err2'),
 (0.013867

In [58]:
# Model Accuracy
print('Test Acc: %.3f' % rf.score(X_test, y_test))

Test Acc: 0.912


In [59]:
# Calculate classification report
from sklearn.metrics import classification_report
predictions = rf.predict(X_test)
print(classification_report(y_test, predictions,
                            target_names=target_names))

                precision    recall  f1-score   support

     CONFIRMED       0.84      0.78      0.81       404
FALSE POSITIVE       0.82      0.86      0.84       435
     CANDIDATE       0.99      1.00      0.99       909

      accuracy                           0.91      1748
     macro avg       0.88      0.88      0.88      1748
  weighted avg       0.91      0.91      0.91      1748



# Save the Model

In [60]:
# save your model by updating "your_name" with your name
import joblib
filename = 'random_forest.joblib'
joblib.dump(rf, filename)

['random_forest.joblib']

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [61]:
# Create the GridSearchCV model
# Create the GridSearch estimator along with a parameter object containing the values to adjust
from sklearn.model_selection import GridSearchCV

In [62]:
params = rf.get_params(deep=True)
params 

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 200,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [63]:
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [1],
    'min_samples_split': [2],
    'n_estimators': [100, 200]
}

In [64]:
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [65]:
rf.get_params(deep=True)

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 200,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [66]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 16 candidates, totalling 48 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   21.8s
[Parallel(n_jobs=-1)]: Done  48 out of  48 | elapsed:   30.6s finished


GridSearchCV(cv=3, estimator=RandomForestClassifier(n_estimators=200),
             n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [80, 90, 100, 110],
                         'max_features': [2, 3], 'min_samples_leaf': [1],
                         'min_samples_split': [2], 'n_estimators': [100, 200]},
             verbose=2)

In [67]:
print(grid_search.best_params_)

{'bootstrap': True, 'max_depth': 90, 'max_features': 3, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}


In [68]:
print(grid_search.best_score_)

0.8786945213260872


In [69]:
# Make predictions with the hypertuned model
predictions = grid_search.predict(X_test)
predictions

array(['CONFIRMED', 'FALSE POSITIVE', 'FALSE POSITIVE', ...,
       'FALSE POSITIVE', 'FALSE POSITIVE', 'CANDIDATE'], dtype=object)

In [70]:
print('Test Acc: %.3f' % grid_search.score(X_test, y_test))

Test Acc: 0.894


In [71]:
# Calculate classification report
print(classification_report(y_test, predictions,
                            target_names=target_names))

                precision    recall  f1-score   support

     CONFIRMED       0.84      0.71      0.77       404
FALSE POSITIVE       0.81      0.86      0.83       435
     CANDIDATE       0.95      1.00      0.97       909

      accuracy                           0.89      1748
     macro avg       0.87      0.85      0.86      1748
  weighted avg       0.89      0.89      0.89      1748

